name: ecommerceapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  modal_progress_hud: ^0.1.3
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - material/images/icons/




  fonts:
    - family: Pacifico
      fonts:
          - asset: material/fonts/Pacifico-Regular.ttf
